name: Tests
on:
  - push
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.8"
          enable-cache: true

      - name: Sync project
        run: uv sync --locked --all-extras --dev

      - name: Check format
        run: uv run ruff format --diff

      - name: Static analysis
        run: uv run ruff check

      - name: Type checking
        run: uv run basedpyright

      - name: Unit tests
        run: uv run pytest

      - name: Build
        run: uv build
